# Generated by Django 4.2.4 on 2023-10-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('Primary school', 'Primary School'), ('Secondary School', 'Secondary School'), ('Tertiary Level', 'Tertiary Level')], max_length=100, null=True),
        ),
    ]
