# Generated by Django 4.2.6 on 2023-10-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customuser_is_admin_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cash_balance',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
