# Generated by Django 4.2.6 on 2023-10-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_cash_balance_customuser_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
    ]
