# Generated by Django 4.2.4 on 2023-10-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_downloadrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='level_of_education',
            field=models.CharField(choices=[('primary-school', 'Primary School'), ('high-school', 'High School'), ('tertiary', 'Tertiary Institutions')], max_length=50),
        ),
    ]
