# Generated by Django 4.2.6 on 2023-10-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
